remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: ETH Zurich Autonomous Systems Lab
description: Datasets and open-source code from the Autonomous Systems Lab (ASL) at ETH Zurich, led by Prof. Roland Siegwart.

collections:
  datasets:
    output: true
    permalink: /datasets/:name/

defaults:
  - scope:
      path: ""
      type: "datasets"
    values:
      layout: dataset

logo: /assets/img/logo.png
